name: stringi for R (ICU bundle; ubuntu-latest)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        # https://cran.r-project.org/bin/linux/ubuntu/
        sudo apt install --no-install-recommends software-properties-common dirmngr
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
        sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
        sudo apt-get -y upgrade
        sudo apt-get -y install libcurl4-openssl-dev r-base-dev devscripts
        sudo Rscript -e "install.packages(c('tinytest', 'Rcpp'))"
    - name: Install stringi
      run: |
        sudo R CMD INSTALL . --configure-args='--disable-pkg-config'
    - name: Test stringi
      run: |
        sudo Rscript -e 'source(".devel/tinytest.R")'
        LC_ALL="pl_PL.UTF-8" Rscript -e 'source(".devel/tinytest.R")'
        LC_ALL="C" Rscript -e 'source(".devel/tinytest.R")'
