name: stringi for R (system ICU)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest}
          - {os: ubuntu-20.04}

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo apt-get -y install libcurl4-openssl-dev r-base-dev devscripts libicu-dev language-pack-pl
        sudo Rscript -e "install.packages(c('tinytest', 'Rcpp'))"
    - name: Install stringi
      run: |
        sudo R CMD INSTALL .
    - name: Test stringi
      run: |
        Rscript -e 'source(".devel/tinytest.R")'
